name: Make Release

on:
    workflow_dispatch:
    push:
        tags: [ 'v*' ]

permissions:
    contents: read

jobs:
    release:
        name: Build and Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Cache Unity Library
              uses: actions/cache@v4
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: |
                      Library-

            -   name: Build the `.unitypackage` File
                uses: game-ci/unity-builder@v4
                env:
                    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                with:
                    targetPlatform: StandaloneLinux64
                    executeMethod: ArikoBuilder.BuildPackage

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: Builds/Ariko.unitypackage
                  token: ${{ secrets.GITHUB_TOKEN }}
