name: Run Tests

on:
    workflow_dispatch:
    workflow_call:
    pull_request:
        branches: [ main ]
    push:
        tags: [ 'v*' ]

permissions:
    contents: read

jobs:
    test:
        name: Run EditMode and PlayMode Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Cache Unity Library
              uses: actions/cache@v4
              with:
                  path: Library
                  key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                  restore-keys: |
                      Library-

            - name: Run Unity Tests
              uses: game-ci/unity-test-runner@v4
              env:
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              with:
                  testMode: All

            - name: Upload Test Results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: Test-Results
                  path: ${{ runner.temp }}/test-results/**/*.xml
                  retention-days: 7
